export type NoticeLanguage = "en" | "th" | "lo"

export type NoticeTranslations = {
    modal: {
        eyebrow: string
        noticeHeading: string
        languageLabel: string
        languageLoadingLabel: string
        experienceSectionLabel: string
        experienceBody: string
        liabilitySectionLabel: string
        liabilityBody: string
        religiousSectionLabel: string
        religiousBody: string
        ageSectionLabel: string
        ageBody: string
        safetySectionLabel: string
        safetyBody: string
        legalLinksLabel: string
        privacyLink: string
        termsLink: string
        consentScrollRegionLabel: string
        scrollToEndHint: string
        checkboxMain: string
        checkboxSub: string
        enterButton: string
    }
    cookies: {
        bannerTitle: string
        bannerDescription: string
        managePreferences: string
        acceptAll: string
        rejectAll: string
        savePreferences: string
        preferencesTitle: string
        preferencesDescription: string
        essentialTitle: string
        essentialDescription: string
        analyticsTitle: string
        analyticsDescription: string
        marketingTitle: string
        marketingDescription: string
        alwaysOnLabel: string
        learnMoreLabel: string
    }
}

export const NOTICE_LANGUAGE_OPTIONS: Array<{
    value: NoticeLanguage
    label: string
}> = [
    { value: "en", label: "English" },
    { value: "th", label: "ไทย" },
    { value: "lo", label: "ລາວ" },
]

const NOTICE_TRANSLATIONS: Record<NoticeLanguage, NoticeTranslations> = {
    en: {
        modal: {
            eyebrow: "Before entering your fate",
            noticeHeading: "Notice & Consent",
            languageLabel: "Language",
            languageLoadingLabel: "Loading translation...",
            experienceSectionLabel: "About this experience",
            experienceBody:
                "AskingFate uses <b>Tarot</b> and <b>Astrology</b> (Western & Vedic) as symbolic reflection tools — not accurate fortune-telling — and cannot replace professional advice. Results may <b>not align</b> with personal or religious beliefs.",
            liabilitySectionLabel: "Limitation of Liability",
            liabilityBody:
                "All interpretations, readings, and astrological analyses generated by this service are provided <b>strictly for entertainment and personal self-reflection purposes</b>. Under no circumstances shall the content produced by AskingFate be construed as professional counsel — whether medical, psychological, financial, legal, or otherwise — nor shall it be regarded as a statement of objective fact, an absolute truth, or a definitive judgment upon any matter of significance in the User's life. The User expressly acknowledges that any decision to act upon, rely upon, or otherwise accord weight to such content <b>without independent verification, corroborating evidence, or the guidance of a duly qualified professional</b> is undertaken entirely at the User's own risk and sole discretion. The Provider, its affiliates, officers, employees, and agents shall bear <b>no liability whatsoever</b> for any loss, damage, or adverse consequence — whether direct, indirect, incidental, consequential, or otherwise — arising from such reliance. Furthermore, content generated by this service <b>shall not be cited, submitted, introduced as evidence, or otherwise relied upon in any legal, judicial, arbitral, administrative, or regulatory proceeding</b>, and the Provider disclaims all responsibility for any attempt to do so.",
            religiousSectionLabel: "Religious & Cultural Sensitivity",
            religiousBody:
                "This service employs tarot divination and astrological methodologies that may be <b>incompatible with, contrary to, or expressly prohibited by</b> certain religious doctrines, ecclesiastical laws, cultural traditions, or systems of spiritual belief. The Provider makes <b>no representation or warranty</b> regarding the compatibility of this service with any particular faith tradition, denomination, sect, or religious order. The Provider shall not be held liable for any consequence whatsoever arising from the User's engagement with this service, including but not limited to <b>excommunication, ecclesiastical censure, religious penalties, spiritual sanctions, loss of communal standing, disciplinary action imposed by religious authorities</b>, or any other adverse outcome attributable to the User's participation. By proceeding, the User acknowledges and accepts full responsibility for determining whether the use of this service is consistent with the User's own religious obligations, spiritual convictions, and community standards.",
            ageSectionLabel: "Age Eligibility",
            ageBody:
                "This service is <b>not directed to, and may not be used by, children under thirteen (13) years of age</b>. By proceeding, the User represents and warrants that the User is at least thirteen (13) years old. If the User is under eighteen (18) years of age, the User must use this service only with the involvement, supervision, and consent of a parent or legal guardian, and the Provider may limit, filter, or withhold certain features, prompts, or responses accordingly.",
            safetySectionLabel: "Sensitive Content & Moderation",
            safetyBody:
                "The Provider respects lawful freedom of expression; however, the Provider reserves the right, in its sole discretion, to <b>filter, restrict, refuse, or moderate</b> prompts, responses, or other content involving sexual material, nudity, exploitation, grooming, abuse, self-harm, suicide, eating disorders, substance misuse, criminal conduct, harassment, hateful conduct, extremism, or graphic violence. For Users under eighteen (18), moderation standards shall be <b>materially more restrictive</b>. In particular, responses to minors may be omitted, summarized, sanitized, or declined where content concerns sexual themes, explicit anatomy, fetishes, intimate conduct, coercive dynamics, adult-minor relationships, or any other topic that may be unsafe, age-inappropriate, exploitative, or unlawful. The Provider may also refuse content that could facilitate illegal acts, exploit vulnerability, or endanger a minor's physical, mental, or emotional well-being.",
            legalLinksLabel: "Related policies",
            privacyLink: "Privacy Policy",
            termsLink: "Terms of Service",
            consentScrollRegionLabel: "Notice and consent text",
            scrollToEndHint: "Scroll to the bottom to continue.",
            checkboxMain:
                "I acknowledge the disclaimer and limitations of liability.",
            checkboxSub:
                "I understand this content is for entertainment and self-reflection only.",
            enterButton: "Enter the Reading",
        },
        cookies: {
            bannerTitle: "Cookie preferences",
            bannerDescription:
                "AskingFate uses cookies for essential site functions and, with your permission, analytics and future personalization. You can accept all, reject non-essential cookies, or manage preferences below.",
            managePreferences: "Manage Preferences",
            acceptAll: "Accept All",
            rejectAll: "Reject All",
            savePreferences: "Save Preferences",
            preferencesTitle: "Manage cookie categories",
            preferencesDescription:
                "Non-essential categories stay off until you explicitly enable them.",
            essentialTitle: "Essential cookies",
            essentialDescription:
                "Required for core site functions, secure sessions, and anonymous star balance continuity.",
            analyticsTitle: "Analytics cookies",
            analyticsDescription:
                "Allows privacy-friendly Vercel Analytics so we can understand traffic and improve the product.",
            marketingTitle: "Marketing cookies",
            marketingDescription:
                "Reserved for future campaign or personalization tools. No marketing scripts run unless you opt in.",
            alwaysOnLabel: "Always on",
            learnMoreLabel: "Learn more in our Privacy Policy",
        },
    },
    th: {
        modal: {
            eyebrow: "ก่อนเข้าสู่ดวงชะตา",
            noticeHeading: "Notice & Consent",
            languageLabel: "ภาษา",
            languageLoadingLabel: "กำลังโหลดคำแปล...",
            experienceSectionLabel: "เกี่ยวกับประสบการณ์นี้",
            experienceBody:
                "AskingFate ใช้ <b>ไพ่ทาโรต์</b> และ <b>โหราศาสตร์</b> (Western & Vedic) เป็นสื่อสะท้อนเชิงสัญลักษณ์ ไม่ใช่การทำนายดวงที่แม่นยำ และไม่สามารถทดแทนคำแนะนำจากผู้เชี่ยวชาญ ผลลัพธ์อาจ<b>ไม่สอดคล้อง</b>กับความเชื่อทางศาสนาหรือค่านิยมส่วนบุคคล",
            liabilitySectionLabel: "ข้อจำกัดความรับผิด",
            liabilityBody:
                "คำทำนาย การตีความ และการวิเคราะห์ทางโหราศาสตร์ทั้งหมดที่สร้างขึ้นโดยบริการนี้จัดทำขึ้น<b>เพื่อความบันเทิงและการสะท้อนตนเองเท่านั้น</b> ไม่ว่าในกรณีใดก็ตาม เนื้อหาที่ผลิตโดย AskingFate ไม่อาจถูกตีความเป็นคำแนะนำจากผู้เชี่ยวชาญ — ไม่ว่าจะเป็นด้านการแพทย์ จิตวิทยา การเงิน กฎหมาย หรืออื่นใด — และไม่ถือเป็นข้อเท็จจริงเชิงวัตถุวิสัย ความจริงที่แน่นอน หรือการตัดสินขั้นสุดท้ายในเรื่องสำคัญของชีวิตผู้ใช้ ผู้ใช้รับทราบโดยชัดแจ้งว่าการตัดสินใจกระทำการ พึ่งพา หรือให้น้ำหนักแก่เนื้อหาดังกล่าว<b>โดยปราศจากการตรวจสอบอย่างเป็นอิสระ หลักฐานเชิงประจักษ์ หรือคำแนะนำจากผู้เชี่ยวชาญที่มีคุณสมบัติเหมาะสม</b>ถือเป็นความเสี่ยงและดุลยพินิจของผู้ใช้แต่เพียงผู้เดียว ผู้ให้บริการ บริษัทในเครือ กรรมการ พนักงาน และตัวแทน<b>ไม่มีความรับผิดใด ๆ ทั้งสิ้น</b>สำหรับความสูญเสีย ความเสียหาย หรือผลกระทบอันไม่พึงประสงค์ — ไม่ว่าจะเป็นทางตรง ทางอ้อม โดยบังเอิญ สืบเนื่อง หรืออื่นใด — ที่เกิดจากการพึ่งพาดังกล่าว นอกจากนี้ เนื้อหาที่สร้างขึ้นโดยบริการนี้<b>ไม่สามารถนำไปอ้างอิง ยื่น เสนอเป็นหลักฐาน หรือพึ่งพาในกระบวนการทางกฎหมาย ทางตุลาการ ทางอนุญาโตตุลาการ ทางปกครอง หรือทางกำกับดูแลใด ๆ</b> และผู้ให้บริการปฏิเสธความรับผิดชอบทั้งหมดสำหรับความพยายามใด ๆ ในการกระทำเช่นนั้น",
            religiousSectionLabel: "ความอ่อนไหวทางศาสนาและวัฒนธรรม",
            religiousBody:
                "บริการนี้ใช้วิธีการทำนายด้วยไพ่ทาโรต์และโหราศาสตร์ซึ่งอาจ<b>ไม่สอดคล้อง ขัดแย้ง หรือถูกห้ามโดยชัดแจ้ง</b>ตามหลักคำสอนทางศาสนา กฎหมายทางศาสนจักร ประเพณีทางวัฒนธรรม หรือระบบความเชื่อทางจิตวิญญาณบางประการ ผู้ให้บริการ<b>ไม่ได้รับรองหรือรับประกัน</b>ใด ๆ เกี่ยวกับความเข้ากันได้ของบริการนี้กับศาสนา นิกาย สำนัก หรือคณะสงฆ์ใดเป็นการเฉพาะ ผู้ให้บริการจะไม่รับผิดชอบต่อผลกระทบใด ๆ ที่เกิดจากการใช้บริการของผู้ใช้ รวมถึงแต่ไม่จำกัดเพียง<b>การถูกขับออกจากศาสนา การตำหนิจากศาสนจักร บทลงโทษทางศาสนา การลงทัณฑ์ทางจิตวิญญาณ การสูญเสียสถานะในชุมชน การลงโทษทางวินัยที่กำหนดโดยผู้มีอำนาจทางศาสนา</b> หรือผลลัพธ์อันไม่พึงประสงค์อื่นใดที่เกิดจากการมีส่วนร่วมของผู้ใช้ การดำเนินการต่อถือว่าผู้ใช้รับทราบและยอมรับความรับผิดชอบอย่างเต็มที่ในการพิจารณาว่าการใช้บริการนี้สอดคล้องกับพันธกรณีทางศาสนา ความเชื่อทางจิตวิญญาณ และมาตรฐานชุมชนของผู้ใช้เอง",
            ageSectionLabel: "ข้อกำหนดอายุผู้ใช้",
            ageBody:
                "บริการนี้<b>มิได้มีเจตนาให้เด็กอายุต่ำกว่าสิบสาม (13) ปีใช้งาน และห้ามเด็กอายุต่ำกว่าสิบสาม (13) ปีใช้บริการนี้</b> โดยการดำเนินการต่อ ผู้ใช้รับรองและยืนยันว่าตนมีอายุอย่างน้อยสิบสาม (13) ปีบริบูรณ์ หากผู้ใช้มีอายุต่ำกว่าสิบแปด (18) ปี ผู้ใช้ต้องใช้บริการนี้ภายใต้การมีส่วนร่วม การกำกับดูแล และความยินยอมของบิดามารดาหรือผู้ปกครองโดยชอบด้วยกฎหมาย และผู้ให้บริการอาจจำกัด กรอง หรือระงับคุณสมบัติ คำสั่ง หรือคำตอบบางประเภทตามความเหมาะสม",
            safetySectionLabel: "เนื้อหาอ่อนไหวและการกำกับดูแล",
            safetyBody:
                "ผู้ให้บริการเคารพเสรีภาพในการแสดงออกที่ชอบด้วยกฎหมาย อย่างไรก็ดี ผู้ให้บริการขอสงวนสิทธิแต่เพียงผู้เดียวในการ<b>กรอง จำกัด ปฏิเสธ หรือควบคุมดูแล</b>คำสั่ง คำตอบ หรือเนื้อหาอื่นใดที่เกี่ยวข้องกับเรื่องทางเพศ ภาพเปลือย การแสวงหาประโยชน์ การชักจูงเด็ก การล่วงละเมิด การทำร้ายตนเอง การฆ่าตัวตาย ความผิดปกติด้านการกิน การใช้สารเสพติด การกระทำผิดกฎหมาย การคุกคาม ความเกลียดชัง แนวคิดสุดโต่ง หรือความรุนแรงอย่างโจ่งแจ้ง สำหรับผู้ใช้ที่มีอายุต่ำกว่าสิบแปด (18) ปี มาตรฐานการกำกับดูแลจะ<b>เข้มงวดกว่าปกติอย่างมีนัยสำคัญ</b> โดยเฉพาะอย่างยิ่ง คำตอบสำหรับผู้เยาว์อาจถูกตัดทอน สรุป ปรับให้ปลอดภัย หรือปฏิเสธ หากเกี่ยวข้องกับประเด็นทางเพศ กายวิภาคโดยเปิดเผย รสนิยมทางเพศเชิงเร้าอารมณ์ พฤติกรรมใกล้ชิด พลวัตเชิงบังคับ ความสัมพันธ์ระหว่างผู้ใหญ่กับผู้เยาว์ หรือหัวข้ออื่นใดที่อาจไม่ปลอดภัย ไม่เหมาะสมกับวัย มีลักษณะแสวงหาประโยชน์ หรือผิดกฎหมาย ผู้ให้บริการอาจปฏิเสธเนื้อหาที่อาจเอื้อให้เกิดการกระทำผิดกฎหมาย ฉวยโอกาสจากความเปราะบาง หรือเป็นอันตรายต่อสวัสดิภาพทางกาย จิตใจ หรืออารมณ์ของผู้เยาว์ได้เช่นกัน",
            legalLinksLabel: "นโยบายที่เกี่ยวข้อง",
            privacyLink: "นโยบายความเป็นส่วนตัว",
            termsLink: "ข้อกำหนดการใช้งาน",
            consentScrollRegionLabel: "ข้อความประกาศและความยินยอม",
            scrollToEndHint: "เลื่อนลงจนสุดเพื่อดำเนินการต่อ",
            checkboxMain:
                "ฉันรับทราบข้อจำกัดความรับผิดชอบและข้อสงวนสิทธิ์แล้ว",
            checkboxSub:
                "ฉันเข้าใจว่าเนื้อหานี้มีไว้เพื่อความบันเทิงและการสะท้อนตนเองเท่านั้น",
            enterButton: "เข้าสู่การทำนาย",
        },
        cookies: {
            bannerTitle: "การตั้งค่าคุกกี้",
            bannerDescription:
                "AskingFate ใช้คุกกี้สำหรับการทำงานที่จำเป็นของเว็บไซต์ และจะใช้คุกกี้วิเคราะห์หรือการปรับแต่งเพิ่มเติมเมื่อคุณอนุญาตเท่านั้น คุณสามารถยอมรับทั้งหมด ปฏิเสธคุกกี้ที่ไม่จำเป็น หรือจัดการการตั้งค่าได้ด้านล่าง",
            managePreferences: "จัดการการตั้งค่า",
            acceptAll: "ยอมรับทั้งหมด",
            rejectAll: "ปฏิเสธทั้งหมด",
            savePreferences: "บันทึกการตั้งค่า",
            preferencesTitle: "จัดการหมวดหมู่คุกกี้",
            preferencesDescription:
                "หมวดหมู่ที่ไม่จำเป็นจะยังคงปิดไว้จนกว่าคุณจะเปิดใช้งานเอง",
            essentialTitle: "คุกกี้ที่จำเป็น",
            essentialDescription:
                "จำเป็นต่อการทำงานหลักของเว็บไซต์ ความปลอดภัยของเซสชัน และความต่อเนื่องของยอดดาวแบบไม่ลงชื่อเข้าใช้",
            analyticsTitle: "คุกกี้วิเคราะห์",
            analyticsDescription:
                "อนุญาตให้ใช้ Vercel Analytics เพื่อช่วยให้เราเข้าใจการใช้งานและปรับปรุงผลิตภัณฑ์",
            marketingTitle: "คุกกี้การตลาด",
            marketingDescription:
                "สงวนไว้สำหรับเครื่องมือการตลาดหรือการปรับแต่งในอนาคต จะไม่มีสคริปต์การตลาดทำงานจนกว่าคุณจะเลือกเปิด",
            alwaysOnLabel: "เปิดตลอดเวลา",
            learnMoreLabel: "อ่านเพิ่มเติมในนโยบายความเป็นส่วนตัว",
        },
    },
    lo: {
        modal: {
            eyebrow: "ກ່ອນເຂົ້າສູ່ດວງຊະຕາ",
            noticeHeading: "Notice & Consent",
            languageLabel: "ພາສາ",
            languageLoadingLabel: "ກຳລັງໂຫລດຄຳແປ...",
            experienceSectionLabel: "ກ່ຽວກັບປະສົບການນີ້",
            experienceBody:
                "AskingFate ໃຊ້ <b>ໄພ່ທາໂຣ</b> ແລະ <b>ໂຫລາສາດ</b> (Western & Vedic) ເປັນສື່ສະທ້ອນເຊີງສັນຍາລັກ ບໍ່ແມ່ນການທຳນາຍດວງທີ່ແມ່ນຢຳ ແລະ ບໍ່ສາມາດທົດແທນຄຳແນະນຳຈາກຜູ້ຊ່ຽວຊານ ຜົນໄດ້ຮັບອາດ<b>ບໍ່ສອດຄ່ອງ</b>ກັບຄວາມເຊື່ອທາງສາສະໜາ ຫຼື ຄ່ານິຍົມສ່ວນບຸກຄົນ",
            liabilitySectionLabel: "ຂໍ້ຈຳກັດຄວາມຮັບຜິດ",
            liabilityBody:
                "ຄຳທຳນາຍ ການຕີຄວາມ ແລະ ການວິເຄາະທາງໂຫລາສາດທັງໝົດທີ່ສ້າງຂຶ້ນໂດຍບໍລິການນີ້ຈັດທຳຂຶ້ນ<b>ເພື່ອຄວາມບັນເທີງ ແລະ ການສະທ້ອນຕົນເອງເທົ່ານັ້ນ</b> ບໍ່ວ່າໃນກໍລະນີໃດກໍ່ຕາມ ເນື້ອຫາທີ່ຜະລິດໂດຍ AskingFate ບໍ່ອາດຖືກຕີຄວາມເປັນຄຳແນະນຳຈາກຜູ້ຊ່ຽວຊານ — ບໍ່ວ່າຈະເປັນດ້ານການແພດ ຈິດຕະວິທະຍາ ການເງິນ ກົດໝາຍ ຫຼື ອື່ນໃດ — ແລະ ບໍ່ຖືເປັນຂໍ້ເທັດຈິງເຊີງວັດຖຸວິໄສ ຄວາມຈິງທີ່ແນ່ນອນ ຫຼື ການຕັດສິນຂັ້ນສຸດທ້າຍໃນເລື່ອງສຳຄັນຂອງຊີວິດຜູ້ໃຊ້ ຜູ້ໃຊ້ຮັບຊາບໂດຍຊັດແຈ້ງວ່າການຕັດສິນໃຈກະທຳການ ເພິ່ງພາ ຫຼື ໃຫ້ນ້ຳໜັກແກ່ເນື້ອຫາດັ່ງກ່າວ<b>ໂດຍປາສະຈາກການກວດສອບຢ່າງເປັນອິດສະຫຼະ ຫຼັກຖານເຊີງປະຈັກ ຫຼື ຄຳແນະນຳຈາກຜູ້ຊ່ຽວຊານທີ່ມີຄຸນສົມບັດເໝາະສົມ</b>ຖືເປັນຄວາມສ່ຽງ ແລະ ດຸລະພິນິດຂອງຜູ້ໃຊ້ແຕ່ພຽງຜູ້ດຽວ ຜູ້ໃຫ້ບໍລິການ ບໍລິສັດໃນເຄືອ ກຳມະການ ພະນັກງານ ແລະ ຕົວແທນ<b>ບໍ່ມີຄວາມຮັບຜິດໃດໆທັງສິ້ນ</b>ສຳລັບຄວາມສູນເສຍ ຄວາມເສຍຫາຍ ຫຼື ຜົນກະທົບອັນບໍ່ພຶງປະສົງ — ບໍ່ວ່າຈະເປັນທາງກົງ ທາງອ້ອມ ໂດຍບັງເອີນ ສືບເນື່ອງ ຫຼື ອື່ນໃດ — ທີ່ເກີດຈາກການເພິ່ງພາດັ່ງກ່າວ ນອກຈາກນີ້ ເນື້ອຫາທີ່ສ້າງຂຶ້ນໂດຍບໍລິການນີ້<b>ບໍ່ສາມາດນຳໄປອ້າງອີງ ຍື່ນ ສະເໜີເປັນຫຼັກຖານ ຫຼື ເພິ່ງພາໃນຂະບວນການທາງກົດໝາຍ ທາງຕຸລາການ ທາງອະນຸຍາໂຕຕຸລາການ ທາງປົກຄອງ ຫຼື ທາງກຳກັບເບິ່ງແຍງໃດໆ</b> ແລະ ຜູ້ໃຫ້ບໍລິການປະຕິເສດຄວາມຮັບຜິດຊອບທັງໝົດສຳລັບຄວາມພະຍາຍາມໃດໆໃນການກະທຳເຊັ່ນນັ້ນ",
            religiousSectionLabel: "ຄວາມອ່ອນໄຫວທາງສາສະໜາ ແລະ ວັດທະນະທຳ",
            religiousBody:
                "ບໍລິການນີ້ໃຊ້ວິທີການທຳນາຍດ້ວຍໄພ່ທາໂຣ ແລະ ໂຫລາສາດ ເຊິ່ງອາດ<b>ບໍ່ສອດຄ່ອງ ຂັດແຍ່ງ ຫຼື ຖືກຫ້າມໂດຍຊັດແຈ້ງ</b>ຕາມຫຼັກຄຳສອນທາງສາສະໜາ ກົດໝາຍທາງສາສະໜະຈັກ ປະເພນີທາງວັດທະນະທຳ ຫຼື ລະບົບຄວາມເຊື່ອທາງຈິດວິນຍານບາງປະການ ຜູ້ໃຫ້ບໍລິການ<b>ບໍ່ໄດ້ຮັບຮອງ ຫຼື ຮັບປະກັນ</b>ໃດໆກ່ຽວກັບຄວາມເຂົ້າກັນໄດ້ຂອງບໍລິການນີ້ກັບສາສະໜາ ນິກາຍ ສຳນັກ ຫຼື ຄະນະສົງໃດເປັນການສະເພາະ ຜູ້ໃຫ້ບໍລິການຈະບໍ່ຮັບຜິດຊອບຕໍ່ຜົນກະທົບໃດໆທີ່ເກີດຈາກການໃຊ້ບໍລິການຂອງຜູ້ໃຊ້ ລວມເຖິງແຕ່ບໍ່ຈຳກັດພຽງ<b>ການຖືກຂັບອອກຈາກສາສະໜາ ການຕຳໜິຈາກສາສະໜະຈັກ ບົດລົງໂທດທາງສາສະໜາ ການລົງທັນທາງຈິດວິນຍານ ການສູນເສຍສະຖານະໃນຊຸມຊົນ ການລົງໂທດທາງວິໄນທີ່ກຳນົດໂດຍຜູ້ມີອຳນາດທາງສາສະໜາ</b> ຫຼື ຜົນໄດ້ຮັບອັນບໍ່ພຶງປະສົງອື່ນໃດທີ່ເກີດຈາກການມີສ່ວນຮ່ວມຂອງຜູ້ໃຊ້ ການດຳເນີນການຕໍ່ຖືວ່າຜູ້ໃຊ້ຮັບຊາບ ແລະ ຍອມຮັບຄວາມຮັບຜິດຊອບຢ່າງເຕັມທີ່ໃນການພິຈາລະນາວ່າການໃຊ້ບໍລິການນີ້ສອດຄ່ອງກັບພັນທະກິດທາງສາສະໜາ ຄວາມເຊື່ອທາງຈິດວິນຍານ ແລະ ມາດຕະຖານຊຸມຊົນຂອງຜູ້ໃຊ້ເອງ",
            ageSectionLabel: "ຂໍ້ກຳນົດອາຍຸຜູ້ໃຊ້",
            ageBody:
                "ບໍລິການນີ້<b>ບໍ່ໄດ້ຈັດເຮັດຂຶ້ນສຳລັບເດັກທີ່ອາຍຸຕ່ຳກວ່າສິບສາມ (13) ປີ ແລະ ເດັກທີ່ອາຍຸຕ່ຳກວ່າສິບສາມ (13) ປີຫ້າມໃຊ້ບໍລິການນີ້</b> ໂດຍການດຳເນີນການຕໍ່ ຜູ້ໃຊ້ຮັບຮອງ ແລະ ຢືນຢັນວ່າຕົນມີອາຍຸຢ່າງນ້ອຍສິບສາມ (13) ປີບໍລິບູນ ຖ້າຜູ້ໃຊ້ມີອາຍຸຕ່ຳກວ່າສິບແປດ (18) ປີ ຜູ້ໃຊ້ຕ້ອງໃຊ້ບໍລິການນີ້ພາຍໃຕ້ການມີສ່ວນຮ່ວມ ການກຳກັບດູແລ ແລະ ຄວາມຍິນຍອມຂອງພໍ່ແມ່ ຫຼື ຜູ້ປົກຄອງຕາມກົດໝາຍ ແລະ ຜູ້ໃຫ້ບໍລິການອາດຈຳກັດ ກັ່ນກອງ ຫຼື ລະງັບບາງຄຸນສົມບັດ ຄຳສັ່ງ ຫຼື ຄຳຕອບຕາມຄວາມເໝາະສົມ",
            safetySectionLabel: "ເນື້ອຫາອ່ອນໄຫວ ແລະ ການກຳກັບດູແລ",
            safetyBody:
                "ຜູ້ໃຫ້ບໍລິການເຄົາລົບເສລີພາບໃນການສະແດງອອກທີ່ຊອບດ້ວຍກົດໝາຍ ແນວໃດກໍຕາມ ຜູ້ໃຫ້ບໍລິການຂໍສະຫງວນສິດແຕ່ພຽງຜູ້ດຽວໃນການ<b>ກັ່ນກອງ ຈຳກັດ ປະຕິເສດ ຫຼື ກຳກັບດູແລ</b>ຄຳສັ່ງ ຄຳຕອບ ຫຼື ເນື້ອຫາອື່ນໃດທີ່ກ່ຽວກັບເລື່ອງທາງເພດ ພາບໂປ້ເປືອຍ ການຂູດຮີດ ການລໍ້ລວງເດັກ ການລະເມີດ ການທຳຮ້າຍຕົນເອງ ການຂ້າຕົວຕາຍ ຄວາມຜິດປົກກະຕິດ້ານການກິນ ການໃຊ້ສານເສບຕິດ ການກະທຳຜິດກົດໝາຍ ການຄຸກຄາມ ຄວາມກຽດຊັງ ແນວຄິດຮຸນແຮງສຸດຂົດ ຫຼື ຄວາມຮຸນແຮງທີ່ໂຈ່ງແຈ້ງ ສຳລັບຜູ້ໃຊ້ທີ່ອາຍຸຕ່ຳກວ່າສິບແປດ (18) ປີ ມາດຕະຖານການກຳກັບດູແລຈະ<b>ເຂັ້ມງວດກວ່າປົກກະຕິຢ່າງມີນັຍສຳຄັນ</b> ໂດຍສະເພາະ ຄຳຕອບສຳລັບຜູ້ເຍົາອາດຖືກຕັດອອກ ສະຫຼຸບ ປັບໃຫ້ປອດໄພ ຫຼື ປະຕິເສດ ຫາກເນື້ອຫາກ່ຽວກັບປະເດັນທາງເພດ ກາຍະວິພາກແບບເປີດເຜີຍ ຄວາມຕື່ນເຕັ້ນທາງເພດ ພຶດຕິກຳໃກ້ຊິດ ຄວາມສຳພັນແບບບັງຄັບ ຄວາມສຳພັນລະຫວ່າງຜູ້ໃຫຍ່ກັບເດັກ ຫຼື ຫົວຂໍ້ອື່ນໃດທີ່ອາດບໍ່ປອດໄພ ບໍ່ເໝາະສົມກັບໄວ ມີລັກສະນະຂູດຮີດ ຫຼື ຜິດກົດໝາຍ ຜູ້ໃຫ້ບໍລິການອາດປະຕິເສດເນື້ອຫາທີ່ອາດເອື້ອໃຫ້ເກີດການກະທຳຜິດກົດໝາຍ ຂູດຮີດຄວາມເປາະບາງ ຫຼື ເປັນອັນຕະລາຍຕໍ່ສຸຂະພາບກາຍ ຈິດໃຈ ຫຼື ອາລົມຂອງຜູ້ເຍົາໄດ້ເຊັ່ນກັນ",
            legalLinksLabel: "ນະໂຍບາຍທີ່ກ່ຽວຂ້ອງ",
            privacyLink: "ນະໂຍບາຍຄວາມເປັນສ່ວນຕົວ",
            termsLink: "ຂໍ້ກຳນົດການໃຊ້ງານ",
            consentScrollRegionLabel: "ຂໍ້ຄວາມປະກາດ ແລະ ຄວາມຍິນຍອມ",
            scrollToEndHint: "ເລື່ອນລົງຈົນສຸດເພື່ອດຳເນີນການຕໍ່",
            checkboxMain:
                "ຂ້ອຍຮັບຊາບຂໍ້ສະຫງວນສິດ ແລະ ຂໍ້ຈຳກັດຄວາມຮັບຜິດແລ້ວ",
            checkboxSub:
                "ຂ້ອຍເຂົ້າໃຈວ່າເນື້ອຫານີ້ມີໄວ້ເພື່ອຄວາມບັນເທີງ ແລະ ການສະທ້ອນຕົນເອງເທົ່ານັ້ນ",
            enterButton: "ເຂົ້າສູ່ການອ່ານ",
        },
        cookies: {
            bannerTitle: "ການຕັ້ງຄ່າຄຸກກີ",
            bannerDescription:
                "AskingFate ໃຊ້ຄຸກກີສຳລັບການເຮັດວຽກທີ່ຈຳເປັນຂອງເວັບໄຊ ແລະ ຈະໃຊ້ການວິເຄາະ ຫຼື ການປັບແຕ່ງເພີ່ມເຕີມກໍ່ຕໍ່ເມື່ອທ່ານອະນຸຍາດ ທ່ານສາມາດຍອມຮັບທັງໝົດ ປະຕິເສດຄຸກກີທີ່ບໍ່ຈຳເປັນ ຫຼື ຈັດການການຕັ້ງຄ່າໄດ້ດ້ານລຸ່ມ",
            managePreferences: "ຈັດການການຕັ້ງຄ່າ",
            acceptAll: "ຍອມຮັບທັງໝົດ",
            rejectAll: "ປະຕິເສດທັງໝົດ",
            savePreferences: "ບັນທຶກການຕັ້ງຄ່າ",
            preferencesTitle: "ຈັດການໝວດໝູ່ຄຸກກີ",
            preferencesDescription:
                "ໝວດໝູ່ທີ່ບໍ່ຈຳເປັນຈະຖືກປິດໄວ້ຈົນກວ່າທ່ານຈະເປີດໃຊ້ດ້ວຍຕົນເອງ",
            essentialTitle: "ຄຸກກີທີ່ຈຳເປັນ",
            essentialDescription:
                "ຈຳເປັນສຳລັບການເຮັດວຽກຫຼັກຂອງເວັບໄຊ ຄວາມປອດໄພຂອງເຊດຊັນ ແລະ ຄວາມຕໍ່ເນື່ອງຂອງຍອດດາວແບບບໍ່ລົງຊື່ເຂົ້າໃຊ້",
            analyticsTitle: "ຄຸກກີວິເຄາະ",
            analyticsDescription:
                "ອະນຸຍາດໃຫ້ໃຊ້ Vercel Analytics ເພື່ອຊ່ວຍໃຫ້ເຮົາເຂົ້າໃຈການໃຊ້ງານ ແລະ ປັບປຸງຜະລິດຕະພັນ",
            marketingTitle: "ຄຸກກີການຕະຫຼາດ",
            marketingDescription:
                "ສຳຮອງໄວ້ສຳລັບເຄື່ອງມືການຕະຫຼາດ ຫຼື ການປັບແຕ່ງໃນອະນາຄົດ ຈະບໍ່ມີສະຄຣິບການຕະຫຼາດເຮັດວຽກຈົນກວ່າທ່ານຈະເລືອກເປີດ",
            alwaysOnLabel: "ເປີດຕະຫຼອດ",
            learnMoreLabel: "ອ່ານເພີ່ມໃນນະໂຍບາຍຄວາມເປັນສ່ວນຕົວ",
        },
    },
}

export function isSupportedNoticeLanguage(
    value: string,
): value is NoticeLanguage {
    return value === "en" || value === "th" || value === "lo"
}

export function getNoticeTranslations(language: string): NoticeTranslations {
    if (isSupportedNoticeLanguage(language)) {
        return NOTICE_TRANSLATIONS[language]
    }
    return NOTICE_TRANSLATIONS.en
}

export async function loadNoticeTranslations(
    language: string,
): Promise<NoticeTranslations> {
    return getNoticeTranslations(language)
}
