// Wraps the Vite single-file widget build into a TypeScript module so the MCP
// route can import the HTML as a string (guaranteed to be bundled by Next,
// unlike a runtime fs read). Run after `vite build` via `npm run build:widget`.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs"
import { resolve, dirname } from "node:path"
import { fileURLToPath } from "node:url"

const __dirname = dirname(fileURLToPath(import.meta.url))
const repoRoot = resolve(__dirname, "..")

const htmlPath = resolve(repoRoot, "widget/dist/index.html")
const outPath = resolve(repoRoot, "lib/mcp/card-picker-html.ts")

const html = readFileSync(htmlPath, "utf8")

const banner = `// AUTO-GENERATED by \`npm run build:widget\`. Do not edit by hand.
// Source: widget/card-picker/. Single-file, self-contained MCP Apps widget.
/* eslint-disable */
`

const content = `${banner}export const cardPickerHtml = ${JSON.stringify(html)}\n`

mkdirSync(dirname(outPath), { recursive: true })
writeFileSync(outPath, content, "utf8")

console.log(
    `[wrap-widget] wrote ${outPath} (${(html.length / 1024).toFixed(1)} KiB inlined)`,
)
