/**
 * Brief astrological meanings for planet-in-sign and ascendant.
 * Used for display in the birth chart card.
 */

export const ASCENDANT_MEANINGS: Record<string, string> = {
    Aries: "Pioneering, direct, and energetic. Natural leadership and courage.",
    Taurus: "Steady, sensual, and grounded. Values security and beauty.",
    Gemini: "Curious, communicative, and adaptable. Quick mind and versatility.",
    Cancer: "Nurturing, intuitive, and protective. Emotional depth and care.",
    Leo: "Confident, creative, and warm. Natural charisma and self-expression.",
    Virgo: "Analytical, service-oriented, and precise. Practical and discerning.",
    Libra: "Diplomatic, balanced, and relationship-focused. Seeks harmony.",
    Scorpio: "Intense, transformative, and perceptive. Depth and resilience.",
    Sagittarius: "Philosophical, adventurous, and optimistic. Seeks truth and growth.",
    Capricorn: "Ambitious, disciplined, and responsible. Builds lasting structures.",
    Aquarius: "Innovative, humanitarian, and independent. Forward-thinking vision.",
    Pisces: "Compassionate, imaginative, and receptive. Spiritual sensitivity.",
}

export const PLANET_IN_SIGN_MEANINGS: Record<string, Record<string, string>> = {
    Sun: {
        Aries: "Bold, pioneering spirit. Natural confidence and initiative.",
        Taurus: "Steady, sensual nature. Values comfort and stability.",
        Gemini: "Quick-witted, communicative. Versatile and curious.",
        Cancer: "Nurturing, emotional core. Protective and intuitive.",
        Leo: "Radiant, creative self-expression. Natural charisma.",
        Virgo: "Analytical, service-oriented. Practical and discerning.",
        Libra: "Diplomatic, relationship-focused. Seeks balance and beauty.",
        Scorpio: "Intense, transformative. Depth and emotional power.",
        Sagittarius: "Philosophical, adventurous. Optimistic and expansive.",
        Capricorn: "Ambitious, disciplined. Builds lasting achievement.",
        Aquarius: "Innovative, humanitarian. Independent and visionary.",
        Pisces: "Compassionate, imaginative. Spiritual and receptive.",
    },
    Moon: {
        Aries: "Emotionally impulsive, passionate. Quick to feel and act.",
        Taurus: "Emotionally steady, comfort-seeking. Values security.",
        Gemini: "Emotionally curious, communicative. Needs mental connection.",
        Cancer: "Deeply nurturing, intuitive. Strong emotional bonds.",
        Leo: "Warm, generous emotions. Needs recognition and appreciation.",
        Virgo: "Practical emotions, service through care. Analytical feelings.",
        Libra: "Harmony-seeking emotions. Needs partnership and balance.",
        Scorpio: "Intense, transformative emotions. Depth and loyalty.",
        Sagittarius: "Optimistic, freedom-loving emotions. Expansive feelings.",
        Capricorn: "Reserved, responsible emotions. Builds emotional security.",
        Aquarius: "Detached, humanitarian emotions. Values freedom and friendship.",
        Pisces: "Compassionate, dreamy emotions. Spiritual and sensitive.",
    },
    Mercury: {
        Aries: "Quick, direct thinking. Pioneering ideas and bold communication.",
        Taurus: "Steady, practical mind. Patient and methodical thinking.",
        Gemini: "Versatile, curious intellect. Natural communicator.",
        Cancer: "Intuitive, emotional thinking. Memory and imagination.",
        Leo: "Creative, confident expression. Dramatic and warm communication.",
        Virgo: "Analytical, precise mind. Detail-oriented and practical.",
        Libra: "Diplomatic, balanced thinking. Seeks fairness and harmony.",
        Scorpio: "Deep, probing mind. Sees beneath the surface.",
        Sagittarius: "Philosophical, expansive thinking. Big-picture ideas.",
        Capricorn: "Strategic, disciplined mind. Practical and ambitious.",
        Aquarius: "Innovative, humanitarian thinking. Original and detached.",
        Pisces: "Imaginative, intuitive mind. Creative and empathetic.",
    },
    Venus: {
        Aries: "Passionate, direct in love. Bold and independent.",
        Taurus: "Sensual, steady in love. Values comfort and beauty.",
        Gemini: "Playful, communicative in love. Needs mental connection.",
        Cancer: "Nurturing, protective in love. Deep emotional bonds.",
        Leo: "Generous, romantic. Loves warmth and appreciation.",
        Virgo: "Practical, service-oriented in love. Thoughtful and refined.",
        Libra: "Harmonious, partnership-focused. Natural in relationships.",
        Scorpio: "Intense, transformative in love. Deep and loyal.",
        Sagittarius: "Adventurous, freedom-loving. Optimistic in love.",
        Capricorn: "Serious, committed in love. Builds lasting bonds.",
        Aquarius: "Unconventional, friendly in love. Values freedom.",
        Pisces: "Romantic, compassionate. Spiritual and devoted.",
    },
    Mars: {
        Aries: "Bold, direct action. Natural courage and initiative.",
        Taurus: "Steady, persistent drive. Patient and determined.",
        Gemini: "Quick, versatile action. Communicative energy.",
        Cancer: "Protective, emotional drive. Defends what matters.",
        Leo: "Confident, creative drive. Dramatic and proud.",
        Virgo: "Precise, service-oriented action. Efficient and practical.",
        Libra: "Diplomatic, balanced action. Seeks fairness.",
        Scorpio: "Intense, transformative drive. Powerful and focused.",
        Sagittarius: "Adventurous, expansive drive. Philosophical energy.",
        Capricorn: "Disciplined, ambitious drive. Strategic and patient.",
        Aquarius: "Innovative, rebellious drive. Humanitarian energy.",
        Pisces: "Intuitive, adaptable drive. Compassionate action.",
    },
    Jupiter: {
        Aries: "Bold optimism, pioneering growth. Confident expansion.",
        Taurus: "Steady growth, material abundance. Patient wisdom.",
        Gemini: "Intellectual expansion, versatile learning. Curious growth.",
        Cancer: "Emotional wisdom, nurturing growth. Protective abundance.",
        Leo: "Generous optimism, creative expansion. Warm wisdom.",
        Virgo: "Practical wisdom, service through growth. Refined expansion.",
        Libra: "Harmonious growth, relationship wisdom. Balanced expansion.",
        Scorpio: "Deep wisdom, transformative growth. Intense expansion.",
        Sagittarius: "Philosophical wisdom, adventurous growth. Natural expansion.",
        Capricorn: "Structured wisdom, ambitious growth. Disciplined expansion.",
        Aquarius: "Humanitarian wisdom, innovative growth. Visionary expansion.",
        Pisces: "Spiritual wisdom, compassionate growth. Imaginative expansion.",
    },
    Saturn: {
        Aries: "Disciplined initiative, patient courage. Structured boldness.",
        Taurus: "Steady responsibility, material discipline. Patient structure.",
        Gemini: "Focused communication, serious learning. Structured thinking.",
        Cancer: "Emotional responsibility, protective structure. Serious care.",
        Leo: "Humble confidence, disciplined creativity. Earned recognition.",
        Virgo: "Natural discipline, practical responsibility. Refined structure.",
        Libra: "Serious partnerships, balanced responsibility. Committed harmony.",
        Scorpio: "Deep discipline, transformative responsibility. Intense structure.",
        Sagittarius: "Structured philosophy, disciplined expansion. Serious growth.",
        Capricorn: "Natural discipline, ambitious structure. Lasting achievement.",
        Aquarius: "Innovative responsibility, structured vision. Serious independence.",
        Pisces: "Compassionate discipline, spiritual structure. Gentle boundaries.",
    },
    Rahu: {
        Aries: "Ambitious pioneering, desire for leadership.",
        Taurus: "Material ambition, desire for security.",
        Gemini: "Intellectual ambition, desire for knowledge.",
        Cancer: "Emotional ambition, desire for belonging.",
        Leo: "Recognition ambition, desire for acclaim.",
        Virgo: "Perfection ambition, desire for service.",
        Libra: "Relationship ambition, desire for harmony.",
        Scorpio: "Transformative ambition, desire for power.",
        Sagittarius: "Philosophical ambition, desire for truth.",
        Capricorn: "Achievement ambition, desire for status.",
        Aquarius: "Innovation ambition, desire for change.",
        Pisces: "Spiritual ambition, desire for transcendence.",
    },
    Ketu: {
        Aries: "Release of ego, spiritual courage.",
        Taurus: "Release of attachment, spiritual grounding.",
        Gemini: "Release of mind, spiritual communication.",
        Cancer: "Release of past, spiritual nurturing.",
        Leo: "Release of pride, spiritual humility.",
        Virgo: "Release of perfection, spiritual service.",
        Libra: "Release of partnership, spiritual balance.",
        Scorpio: "Release of control, spiritual transformation.",
        Sagittarius: "Release of dogma, spiritual truth.",
        Capricorn: "Release of ambition, spiritual discipline.",
        Aquarius: "Release of identity, spiritual freedom.",
        Pisces: "Release of boundaries, spiritual surrender.",
    },
    Ascendant: {}, // Use ASCENDANT_MEANINGS for ascendant sign
}

export function getPlanetMeaning(planet: string, sign: string): string {
    if (planet === "Ascendant") {
        return ASCENDANT_MEANINGS[sign] ?? ""
    }
    const planetMeanings = PLANET_IN_SIGN_MEANINGS[planet]
    if (!planetMeanings) return ""
    return planetMeanings[sign] ?? ""
}
