import { z } from "zod"

/**
 * Standalone daily-verdict schema.
 *
 * Used by `/api/horoscope/verdict` (a small, focused LLM call that ONLY needs
 * the personalized transit aspects to produce the verdict hero). Reused here
 * inside `horoscopeInterpretationSchema` as an OPTIONAL field for backwards
 * compatibility — the body route no longer instructs the model to emit it, so
 * in practice the body call leaves it undefined and the verdict route fills
 * it in from a separate, faster request.
 */
export const dailyVerdictSchema = z.object({
    mood: z
        .enum(["good", "caution", "rest"])
        .describe(
            "Overall day energy. 'good' = supportive flow, take action. 'caution' = high-friction or pressured, slow down. 'rest' = low momentum, recharge instead of pushing.",
        ),
    headline: z
        .string()
        .describe(
            "Short, punchy verdict line (2-8 words). MUST be in the SAME language as the user's question. No astrology jargon.",
        ),
    keyMessage: z
        .object({
            headline: z
                .string()
                .describe(
                    "Short key-message line (2-10 words) summarizing the AI's day-answer. SAME language as question. Plain language, no astrology jargon.",
                ),
            subtitle: z
                .string()
                .describe(
                    "One short sentence (~10-18 words) elaborating on the key-message headline. SAME language as question. Plain language.",
                ),
        })
        .optional()
        .describe(
            "Short headline+subtitle summarizing the day's AI answer. Rendered as a key-message box above the detailed HTML block.",
        ),
    detailedHtml: z
        .string()
        .min(1)
        .describe(
            "Short decorated HTML fragment (1-3 paragraphs) that directly answers the user's question for this specific day, grounded in the personalized aspect picture. May open with how the day feels emotionally/energetically, then the concrete answer. ALLOWED TAGS ONLY: <p>, <strong>, <em>, <b>, <i>, <ul>, <ol>, <li>, <br>, and <span class=\"highlight-gold\">. NO headings (<h1>-<h6>) — the verdict headline already plays that role. Use <span class=\"highlight-gold\">…</span> to highlight 1-3 key phrases (a date, a decision, a watch-out). SAME language as the question. Plain language, no astrology jargon, no markdown.",
        ),
    watchOut: z
        .string()
        .optional()
        .describe(
            "Optional single sentence cautioning what to avoid that day. SAME language as question. Only include when there is a meaningful caution.",
        ),
    focusArea: z
        .string()
        .optional()
        .describe(
            "Optional single canonical life-area label that best summarizes the day's focus. MUST match the relevance.label canonical set in the same language.",
        ),
})

export type DailyVerdict = z.infer<typeof dailyVerdictSchema>

/**
 * Top-level response from `/api/horoscope/verdict`. For non-single-day
 * questions the server returns `{ dailyVerdict: null }` so the client can
 * cheaply discriminate without parsing the LLM output.
 */
export const dailyVerdictResponseSchema = z.object({
    dailyVerdict: dailyVerdictSchema.nullable(),
})

export type DailyVerdictResponse = z.infer<typeof dailyVerdictResponseSchema>

/** Schema for horoscope question interpretation (interpretation, conclusion, suggestions; planet/house meanings use static fallbacks) */
export const horoscopeInterpretationSchema = z.object({
    dailyVerdict: dailyVerdictSchema
        .optional()
        .describe(
            "DEPRECATED on this route: `/api/horoscope/question` no longer instructs the model to emit a dailyVerdict — the verdict is generated by the dedicated `/api/horoscope/verdict` route so it can ship to the UI well before the long-form body finishes streaming. Kept optional here for backwards compatibility with cached / older responses.",
        ),
    aspectInsights: z
        .array(
            z.object({
                aspectKey: z
                    .string()
                    .describe(
                        "Unique aspect key provided in personalized_transit_aspects.",
                    ),
                keyword: z
                    .string()
                    .describe(
                        "One short keyword or compact phrase that summarizes this specific aspect's impact. MUST be in the SAME language as the user's question (Thai question = Thai keyword).",
                    ),
                sentiment: z
                    .enum(["good", "bad", "neutral"])
                    .describe(
                        "Impact tone for this aspect keyword: good, bad, or neutral.",
                    ),
                insight: z
                    .string()
                    .describe(
                        "One short sentence explaining how this aspect affects the user relative to natal baseline. MUST be in the SAME language as the user's question.",
                    ),
                impact: z
                    .string()
                    .describe(
                        "Life-area label for this aspect, e.g. 'Career', 'Finance', 'Relationship', 'Health', 'Family', 'Personal Growth', 'Education', 'Travel'. MUST be in the SAME language as the user's question (Thai question = Thai label such as 'การงาน', 'การเงิน', 'ความรัก').",
                    ),
                intensity: z
                    .enum(["low", "medium", "high"])
                    .describe(
                        "How strongly this aspect affects the user right now: 'high' = major life impact, 'medium' = noticeable influence, 'low' = subtle background energy.",
                    ),
            }),
        )
        .default([])
        .describe(
            "Array of per-aspect quick insights mapped to personalized aspect keys.",
        ),
    interpretation: z
        .string()
        .describe(
            "Main 4-8 sentence horoscope reading. Answer the user's question directly using chart data. When timing is mentioned, use exact date/date-range wording (no vague timing phrases).",
        ),
    conclusion: z
        .string()
        .describe(
            "A short, calming wrap-up that concludes the reading without sounding like a tagline. Keep timing language concrete when present.",
        ),
    suggestions: z
        .array(z.string())
        .max(4)
        .default([])
        .describe(
            "3–4 very short, casual follow-up prompts the user might ask next (single line each; conversational, not textbook). Write in the same language as the question.",
        ),
    relevance: z
        .array(
            z.object({
                label: z
                    .string()
                    .describe(
                        "Life-area label, SAME language as the question. Use one of the canonical domains: Career, Finance, Love, Family, Health, Relationships, Education, Travel, Luck, Spirituality, Reputation, Caution (Thai equivalents allowed when the question is Thai, e.g. 'การงาน', 'การเงิน', 'ความรัก').",
                    ),
                pct: z
                    .number()
                    .min(0)
                    .max(100)
                    .describe(
                        "Integer percentage 0-100 representing how much this life-area dominates the reading. Pcts across the array MUST sum to 100.",
                    ),
            }),
        )
        .max(5)
        .default([])
        .describe(
            "Up to 5 dominant life-areas for this reading, used to render a proportional relevance bar. Sorted descending by pct.",
        ),
})

export type HoroscopeInterpretation = z.infer<
    typeof horoscopeInterpretationSchema
>

export const astrologySummarySchema = z.object({
    transits: z
        .array(
            z.object({
                planet: z
                    .string()
                    .describe("The planet name, e.g., 'Sun', 'Mars'."),
                house: z
                    .string()
                    .describe("The house number as a string, e.g., '1', '7'."),
            }),
        )
        .describe(
            "The top 3 most significant transit-to-natal house influences.",
        ),
    vibeIcon: z
        .string()
        .describe(
            "The Lucide icon name that best represents the overall vibe (e.g., 'Heart', 'Zap', 'Sparkles').",
        ),
    interpretation: z
        .string()
        .describe(
            "The main horoscope reading for the transit day. Focus on feelings and impact, avoid jargon.",
        ),
})

export type AstrologySummary = z.infer<typeof astrologySummarySchema>
